version: 2
jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.6
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace

      # Add deployment key fingerprint for CircleCI to use for a push
      - add_ssh_keys:
          fingerprints:
            - "2f:40:72:72:6a:d5:43:08:1e:42:a4:30:03:e3:f1:05"

      - run:
          name: Trust Github
          command: echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> ~/.ssh/known_hosts

      - run:
          name: Check out target repo and replace content
          command: |
            git clone git@github.com:earth-env-data-science/earth-env-data-science.github.io.git target
            cd target
            rm -rf *
            cp -r /tmp/workspace/_site/* .
            touch .nojekyll
            ls -a

      - run:
          name: Commit results and push to gh-pages
          command: |
            cd target
            git config --global user.name "circleci"
            git add -A
            git commit -m "jekyll book web deploy"
            git push -f origin master

  build_html:
    docker:
      - image: circleci/ruby:2.6
    steps:
      # Attach the built markdown files
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace

      # Grab the the built markdown from the last step
      - run:
          name: Copy over built site files
          command: |
            rm -rf ./_build
            cp -r /tmp/workspace/_build ./

      # Build the site's HTML w/ the base_url for CircleCI artifacts
      - checkout
      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "./Gemfile.lock" }}
            - rails-demo-bundle-v2-

      - run: gem install bundler
      - run: bundle install

      # Store bundle cache
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "./Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Build the website
          command: bundle exec jekyll build

      - persist_to_workspace:
          root: .
          paths:
            - ./_site/

  build_markdown:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      # Get our data and merge with upstream
      - run: sudo apt-get update
      - checkout
      # Update our path
      - run: echo "export PATH=~/.local/bin:$PATH" >> $BASH_ENV
      # Restore cached files to speed things up
      - restore_cache:
          keys:
            - cache-pip

      # Install the packages needed to build our documentation
      # This will depend on your particular package!
      - run: pip install --user nbconvert==5.6.1 jupyter-book==0.5.2

      # Cache some files for a speedup in subsequent builds
      - save_cache:
          key: cache-pip
          paths:
            - ~/.cache/pip

      - run:
          name: Build site markdown
          command: jupyter-book build .

      # Persist the specified paths (see https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs)
      - persist_to_workspace:
          root: .
          paths:
            - ./_build/


# Tell CircleCI to use this workflow when it builds the site
workflows:
  version: 2
  default:
    jobs:
      - build_markdown
      - build_html:
          requires:
            - build_markdown
      - deploy:
          requires:
            - build_html
          filters:
            branches:
              only:
                - master
